---
version: "3"
services:
   2bored2wait:
      build: .
      image: 2bored2wait:latest
      container_name: 2bored2wait
      stdin_open: true
      tty: true
      ports:
         - "80:8080"
         - "25565:25566"
      environment:
         MOJANG_USERNAME: Your Minecraft Username
         MOJANG_PASSWORD: Your Minecraft Password
         BOT_TOKEN: Your Discord Bot Token
